"""Add original_folder and is_deleted to File model

Revision ID: 35c896f13a30
Revises: 6fc4b64aea93
Create Date: 2025-01-13 16:17:36.766412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c896f13a30'
down_revision = '6fc4b64aea93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_folder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('original_folder')

    # ### end Alembic commands ###
