"""Description of changes

Revision ID: 6fc4b64aea93
Revises: 
Create Date: 2025-01-09 15:35:52.497649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc4b64aea93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
